In [1]:
#Dear Student,
#
#Welcome to the world of Basketball Data!
#I'm sure you will enjoy this section of the Python Programming course.
#
#Instructions for this dataset:
# Simply copy ALL the lines in this script by pressing 
# CTRL+A on Windows or CMND+A on Mac and run the Jupyter cell
# Once you have executed the commands the following objects
# will be created:
# Matrices:
# - Salary
# - Games
# - MinutesPlayed
# - FieldGoals
# - FieldGoalAttempts
# - Points
# Lists:
# - Players
# - Seasons
# Dictionaries:
# - Sdict
# - Pdict
#We will understand these inside the course.
#
#Sincerely,
#Kirill Eremenko
#www.superdatascience.com

#Copyright: These datasets were prepared using publicly available data.
#           However, theses scripts are subject to Copyright Laws. 
#           If you wish to use these Python scripts outside of the Python Programming Course
#           by Kirill Eremenko, you may do so by referencing www.superdatascience.com in your work.

#Comments:
#Seasons are labeled based on the first year in the season
#E.g. the 2012-2013 season is preseneted as simply 2012

#Notes and Corrections to the data:
#Kevin Durant: 2006 - College Data Used
#Kevin Durant: 2005 - Proxied With 2006 Data
#Derrick Rose: 2012 - Did Not Play
#Derrick Rose: 2007 - College Data Used
#Derrick Rose: 2006 - Proxied With 2007 Data
#Derrick Rose: 2005 - Proxied With 2007 Data

#Import numpy
import numpy as np

#Seasons
Seasons = ["2005","2006","2007","2008","2009","2010","2011","2012","2013","2014"]
Sdict = {"2005":0,"2006":1,"2007":2,"2008":3,"2009":4,"2010":5,"2011":6,"2012":7,"2013":8,"2014":9}

#Players
Players = ["KobeBryant","JoeJohnson","LeBronJames","CarmeloAnthony","DwightHoward","ChrisBosh","ChrisPaul","KevinDurant","DerrickRose","DwayneWade"]
Pdict = {"KobeBryant":0,"JoeJohnson":1,"LeBronJames":2,"CarmeloAnthony":3,"DwightHoward":4,"ChrisBosh":5,"ChrisPaul":6,"KevinDurant":7,"DerrickRose":8,"DwayneWade":9}

#Salaries
KobeBryant_Salary = [15946875,17718750,19490625,21262500,23034375,24806250,25244493,27849149,30453805,23500000]
JoeJohnson_Salary = [12000000,12744189,13488377,14232567,14976754,16324500,18038573,19752645,21466718,23180790]
LeBronJames_Salary = [4621800,5828090,13041250,14410581,15779912,14500000,16022500,17545000,19067500,20644400]
CarmeloAnthony_Salary = [3713640,4694041,13041250,14410581,15779912,17149243,18518574,19450000,22407474,22458000]
DwightHoward_Salary = [4493160,4806720,6061274,13758000,15202590,16647180,18091770,19536360,20513178,21436271]
ChrisBosh_Salary = [3348000,4235220,12455000,14410581,15779912,14500000,16022500,17545000,19067500,20644400]
ChrisPaul_Salary = [3144240,3380160,3615960,4574189,13520500,14940153,16359805,17779458,18668431,20068563]
KevinDurant_Salary = [0,0,4171200,4484040,4796880,6053663,15506632,16669630,17832627,18995624]
DerrickRose_Salary = [0,0,0,4822800,5184480,5546160,6993708,16402500,17632688,18862875]
DwayneWade_Salary = [3031920,3841443,13041250,14410581,15779912,14200000,15691000,17182000,18673000,15000000]
#Matrix
Salary = np.array([KobeBryant_Salary, JoeJohnson_Salary, LeBronJames_Salary, CarmeloAnthony_Salary, DwightHoward_Salary, ChrisBosh_Salary, ChrisPaul_Salary, KevinDurant_Salary, DerrickRose_Salary, DwayneWade_Salary])

#Games 
KobeBryant_G = [80,77,82,82,73,82,58,78,6,35]
JoeJohnson_G = [82,57,82,79,76,72,60,72,79,80]
LeBronJames_G = [79,78,75,81,76,79,62,76,77,69]
CarmeloAnthony_G = [80,65,77,66,69,77,55,67,77,40]
DwightHoward_G = [82,82,82,79,82,78,54,76,71,41]
ChrisBosh_G = [70,69,67,77,70,77,57,74,79,44]
ChrisPaul_G = [78,64,80,78,45,80,60,70,62,82]
KevinDurant_G = [35,35,80,74,82,78,66,81,81,27]
DerrickRose_G = [40,40,40,81,78,81,39,0,10,51]
DwayneWade_G = [75,51,51,79,77,76,49,69,54,62]
#Matrix
Games = np.array([KobeBryant_G, JoeJohnson_G, LeBronJames_G, CarmeloAnthony_G, DwightHoward_G, ChrisBosh_G, ChrisPaul_G, KevinDurant_G, DerrickRose_G, DwayneWade_G])

#Minutes Played
KobeBryant_MP = [3277,3140,3192,2960,2835,2779,2232,3013,177,1207]
JoeJohnson_MP = [3340,2359,3343,3124,2886,2554,2127,2642,2575,2791]
LeBronJames_MP = [3361,3190,3027,3054,2966,3063,2326,2877,2902,2493]
CarmeloAnthony_MP = [2941,2486,2806,2277,2634,2751,1876,2482,2982,1428]
DwightHoward_MP = [3021,3023,3088,2821,2843,2935,2070,2722,2396,1223]
ChrisBosh_MP = [2751,2658,2425,2928,2526,2795,2007,2454,2531,1556]
ChrisPaul_MP = [2808,2353,3006,3002,1712,2880,2181,2335,2171,2857]
KevinDurant_MP = [1255,1255,2768,2885,3239,3038,2546,3119,3122,913]
DerrickRose_MP = [1168,1168,1168,3000,2871,3026,1375,0,311,1530]
DwayneWade_MP = [2892,1931,1954,3048,2792,2823,1625,2391,1775,1971]
#Matrix
MinutesPlayed = np.array([KobeBryant_MP, JoeJohnson_MP, LeBronJames_MP, CarmeloAnthony_MP, DwightHoward_MP, ChrisBosh_MP, ChrisPaul_MP, KevinDurant_MP, DerrickRose_MP, DwayneWade_MP])

#Field Goals
KobeBryant_FG = [978,813,775,800,716,740,574,738,31,266]
JoeJohnson_FG = [632,536,647,620,635,514,423,445,462,446]
LeBronJames_FG = [875,772,794,789,768,758,621,765,767,624]
CarmeloAnthony_FG = [756,691,728,535,688,684,441,669,743,358]
DwightHoward_FG = [468,526,583,560,510,619,416,470,473,251]
ChrisBosh_FG = [549,543,507,615,600,524,393,485,492,343]
ChrisPaul_FG = [407,381,630,631,314,430,425,412,406,568]
KevinDurant_FG = [306,306,587,661,794,711,643,731,849,238]
DerrickRose_FG = [208,208,208,574,672,711,302,0,58,338]
DwayneWade_FG = [699,472,439,854,719,692,416,569,415,509]
#Matrix
FieldGoals  = np.array([KobeBryant_FG, JoeJohnson_FG, LeBronJames_FG, CarmeloAnthony_FG, DwightHoward_FG, ChrisBosh_FG, ChrisPaul_FG, KevinDurant_FG, DerrickRose_FG, DwayneWade_FG])

#Field Goal Attempts
KobeBryant_FGA = [2173,1757,1690,1712,1569,1639,1336,1595,73,713]
JoeJohnson_FGA = [1395,1139,1497,1420,1386,1161,931,1052,1018,1025]
LeBronJames_FGA = [1823,1621,1642,1613,1528,1485,1169,1354,1353,1279]
CarmeloAnthony_FGA = [1572,1453,1481,1207,1502,1503,1025,1489,1643,806]
DwightHoward_FGA = [881,873,974,979,834,1044,726,813,800,423]
ChrisBosh_FGA = [1087,1094,1027,1263,1158,1056,807,907,953,745]
ChrisPaul_FGA = [947,871,1291,1255,637,928,890,856,870,1170]
KevinDurant_FGA = [647,647,1366,1390,1668,1538,1297,1433,1688,467]
DerrickRose_FGA = [436,436,436,1208,1373,1597,695,0,164,835]
DwayneWade_FGA = [1413,962,937,1739,1511,1384,837,1093,761,1084]
#Matrix
FieldGoalAttempts = np.array([KobeBryant_FGA, JoeJohnson_FGA, LeBronJames_FGA, CarmeloAnthony_FGA, DwightHoward_FGA, ChrisBosh_FGA, ChrisPaul_FGA, KevinDurant_FGA, DerrickRose_FGA, DwayneWade_FGA])

#Points
KobeBryant_PTS = [2832,2430,2323,2201,1970,2078,1616,2133,83,782]
JoeJohnson_PTS = [1653,1426,1779,1688,1619,1312,1129,1170,1245,1154]
LeBronJames_PTS = [2478,2132,2250,2304,2258,2111,1683,2036,2089,1743]
CarmeloAnthony_PTS = [2122,1881,1978,1504,1943,1970,1245,1920,2112,966]
DwightHoward_PTS = [1292,1443,1695,1624,1503,1784,1113,1296,1297,646]
ChrisBosh_PTS = [1572,1561,1496,1746,1678,1438,1025,1232,1281,928]
ChrisPaul_PTS = [1258,1104,1684,1781,841,1268,1189,1186,1185,1564]
KevinDurant_PTS = [903,903,1624,1871,2472,2161,1850,2280,2593,686]
DerrickRose_PTS = [597,597,597,1361,1619,2026,852,0,159,904]
DwayneWade_PTS = [2040,1397,1254,2386,2045,1941,1082,1463,1028,1331]
#Matrix
Points = np.array([KobeBryant_PTS, JoeJohnson_PTS, LeBronJames_PTS, CarmeloAnthony_PTS, DwightHoward_PTS, ChrisBosh_PTS, ChrisPaul_PTS, KevinDurant_PTS, DerrickRose_PTS, DwayneWade_PTS])


In [2]:
KobeBryant_PTS

[2832, 2430, 2323, 2201, 1970, 2078, 1616, 2133, 83, 782]

In [3]:
Players

['KobeBryant',
 'JoeJohnson',
 'LeBronJames',
 'CarmeloAnthony',
 'DwightHoward',
 'ChrisBosh',
 'ChrisPaul',
 'KevinDurant',
 'DerrickRose',
 'DwayneWade']

In [4]:
Games

array([[80, 77, 82, 82, 73, 82, 58, 78,  6, 35],
       [82, 57, 82, 79, 76, 72, 60, 72, 79, 80],
       [79, 78, 75, 81, 76, 79, 62, 76, 77, 69],
       [80, 65, 77, 66, 69, 77, 55, 67, 77, 40],
       [82, 82, 82, 79, 82, 78, 54, 76, 71, 41],
       [70, 69, 67, 77, 70, 77, 57, 74, 79, 44],
       [78, 64, 80, 78, 45, 80, 60, 70, 62, 82],
       [35, 35, 80, 74, 82, 78, 66, 81, 81, 27],
       [40, 40, 40, 81, 78, 81, 39,  0, 10, 51],
       [75, 51, 51, 79, 77, 76, 49, 69, 54, 62]])

In [5]:
Points

array([[2832, 2430, 2323, 2201, 1970, 2078, 1616, 2133,   83,  782],
       [1653, 1426, 1779, 1688, 1619, 1312, 1129, 1170, 1245, 1154],
       [2478, 2132, 2250, 2304, 2258, 2111, 1683, 2036, 2089, 1743],
       [2122, 1881, 1978, 1504, 1943, 1970, 1245, 1920, 2112,  966],
       [1292, 1443, 1695, 1624, 1503, 1784, 1113, 1296, 1297,  646],
       [1572, 1561, 1496, 1746, 1678, 1438, 1025, 1232, 1281,  928],
       [1258, 1104, 1684, 1781,  841, 1268, 1189, 1186, 1185, 1564],
       [ 903,  903, 1624, 1871, 2472, 2161, 1850, 2280, 2593,  686],
       [ 597,  597,  597, 1361, 1619, 2026,  852,    0,  159,  904],
       [2040, 1397, 1254, 2386, 2045, 1941, 1082, 1463, 1028, 1331]])

In [6]:
import numpy as np
mydata = np.arange(0,20)
print(mydata)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [7]:
np.reshape(mydata, (5, 4)) #NOTE: default is opposite to R

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [8]:
matr1 = np.reshape(mydata, (5, 4), order='C')
matr1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [9]:
#Exercise - get to the number 10:
matr1[2, 2]

10

In [10]:
matr2 = np.reshape(mydata, (5, 4), order='F')
matr2

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

In [11]:
#Exercise - get to the number 10:
matr2[0, 2]

10

In [12]:
#OOP Concept:
#np.reshape(mydata, (5, 4))
mydata.reshape((5, 4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

---

In [13]:
r1 = ['I', 'am', 'happy']
r2 = ['What', 'a', 'day']
r3 = [1, 2, 3]

In [14]:
[r1, r2, r3]

[['I', 'am', 'happy'], ['What', 'a', 'day'], [1, 2, 3]]

In [15]:
print(np.array([r1, r2, r3]))

[['I' 'am' 'happy']
 ['What' 'a' 'day']
 ['1' '2' '3']]


---

In [16]:
#Dictionaries

In [17]:
Games

array([[80, 77, 82, 82, 73, 82, 58, 78,  6, 35],
       [82, 57, 82, 79, 76, 72, 60, 72, 79, 80],
       [79, 78, 75, 81, 76, 79, 62, 76, 77, 69],
       [80, 65, 77, 66, 69, 77, 55, 67, 77, 40],
       [82, 82, 82, 79, 82, 78, 54, 76, 71, 41],
       [70, 69, 67, 77, 70, 77, 57, 74, 79, 44],
       [78, 64, 80, 78, 45, 80, 60, 70, 62, 82],
       [35, 35, 80, 74, 82, 78, 66, 81, 81, 27],
       [40, 40, 40, 81, 78, 81, 39,  0, 10, 51],
       [75, 51, 51, 79, 77, 76, 49, 69, 54, 62]])

In [18]:
Games[0]

array([80, 77, 82, 82, 73, 82, 58, 78,  6, 35])

In [19]:
Games[2]

array([79, 78, 75, 81, 76, 79, 62, 76, 77, 69])

In [20]:
Games[2][9]

69

In [21]:
Games[2,-1]

69

In [22]:
Games[2,9]

69

In [23]:
Points[6]

array([1258, 1104, 1684, 1781,  841, 1268, 1189, 1186, 1185, 1564])

In [24]:
Points[6,1]

1104

---

In [25]:
dict1 = {'key1':'val1', 'key2':'val2', 'key3':'val3'} # not ordered

In [26]:
dict1[1]

KeyError: 1

In [27]:
dict1['key2']

'val2'

In [28]:
dict1['key1']

'val1'

In [29]:
dict1

{'key1': 'val1', 'key2': 'val2', 'key3': 'val3'}

In [30]:
dict2= {'Germany': 'I have been here', 'France': 2, 'Spain': True}

In [31]:
dict2

{'Germany': 'I have been here', 'France': 2, 'Spain': True}

In [32]:
dict2['France']

2

---

In [33]:
Pdict['KobeBryant']

0

In [34]:
Games[0]

array([80, 77, 82, 82, 73, 82, 58, 78,  6, 35])

In [35]:
Pdict['DerrickRose']

8

In [36]:
Games[8]

array([40, 40, 40, 81, 78, 81, 39,  0, 10, 51])

In [37]:
Games[Pdict['DerrickRose']]

array([40, 40, 40, 81, 78, 81, 39,  0, 10, 51])

In [38]:
Games[Pdict['DerrickRose']][7]

0

In [39]:
Games[Pdict['DerrickRose']][Sdict['2012']]

0

In [40]:
Points[Pdict['JoeJohnson']][Sdict['2012']]

1170

In [41]:
Points[Pdict['JoeJohnson']]

array([1653, 1426, 1779, 1688, 1619, 1312, 1129, 1170, 1245, 1154])

---

In [42]:
#Matrix Operations

In [43]:
Salary

array([[15946875, 17718750, 19490625, 21262500, 23034375, 24806250,
        25244493, 27849149, 30453805, 23500000],
       [12000000, 12744189, 13488377, 14232567, 14976754, 16324500,
        18038573, 19752645, 21466718, 23180790],
       [ 4621800,  5828090, 13041250, 14410581, 15779912, 14500000,
        16022500, 17545000, 19067500, 20644400],
       [ 3713640,  4694041, 13041250, 14410581, 15779912, 17149243,
        18518574, 19450000, 22407474, 22458000],
       [ 4493160,  4806720,  6061274, 13758000, 15202590, 16647180,
        18091770, 19536360, 20513178, 21436271],
       [ 3348000,  4235220, 12455000, 14410581, 15779912, 14500000,
        16022500, 17545000, 19067500, 20644400],
       [ 3144240,  3380160,  3615960,  4574189, 13520500, 14940153,
        16359805, 17779458, 18668431, 20068563],
       [       0,        0,  4171200,  4484040,  4796880,  6053663,
        15506632, 16669630, 17832627, 18995624],
       [       0,        0,        0,  4822800,  5184480,  55461

In [44]:
#Salary[][]
print (Pdict["LeBronJames"])
print(Sdict["2009"])

2
4


In [45]:
Salary[2][4]

15779912

In [46]:
Salary[Pdict["LeBronJames"]][Sdict["2009"]]

15779912

In [47]:
FieldGoals

array([[978, 813, 775, 800, 716, 740, 574, 738,  31, 266],
       [632, 536, 647, 620, 635, 514, 423, 445, 462, 446],
       [875, 772, 794, 789, 768, 758, 621, 765, 767, 624],
       [756, 691, 728, 535, 688, 684, 441, 669, 743, 358],
       [468, 526, 583, 560, 510, 619, 416, 470, 473, 251],
       [549, 543, 507, 615, 600, 524, 393, 485, 492, 343],
       [407, 381, 630, 631, 314, 430, 425, 412, 406, 568],
       [306, 306, 587, 661, 794, 711, 643, 731, 849, 238],
       [208, 208, 208, 574, 672, 711, 302,   0,  58, 338],
       [699, 472, 439, 854, 719, 692, 416, 569, 415, 509]])

In [48]:
Games

array([[80, 77, 82, 82, 73, 82, 58, 78,  6, 35],
       [82, 57, 82, 79, 76, 72, 60, 72, 79, 80],
       [79, 78, 75, 81, 76, 79, 62, 76, 77, 69],
       [80, 65, 77, 66, 69, 77, 55, 67, 77, 40],
       [82, 82, 82, 79, 82, 78, 54, 76, 71, 41],
       [70, 69, 67, 77, 70, 77, 57, 74, 79, 44],
       [78, 64, 80, 78, 45, 80, 60, 70, 62, 82],
       [35, 35, 80, 74, 82, 78, 66, 81, 81, 27],
       [40, 40, 40, 81, 78, 81, 39,  0, 10, 51],
       [75, 51, 51, 79, 77, 76, 49, 69, 54, 62]])

In [49]:
FieldGoals / Games

/tmp/ipykernel_671/682617760.py:1: RuntimeWarning: invalid value encountered in true_divide
  FieldGoals / Games


array([[12.225     , 10.55844156,  9.45121951,  9.75609756,  9.80821918,
         9.02439024,  9.89655172,  9.46153846,  5.16666667,  7.6       ],
       [ 7.70731707,  9.40350877,  7.8902439 ,  7.84810127,  8.35526316,
         7.13888889,  7.05      ,  6.18055556,  5.84810127,  5.575     ],
       [11.07594937,  9.8974359 , 10.58666667,  9.74074074, 10.10526316,
         9.59493671, 10.01612903, 10.06578947,  9.96103896,  9.04347826],
       [ 9.45      , 10.63076923,  9.45454545,  8.10606061,  9.97101449,
         8.88311688,  8.01818182,  9.98507463,  9.64935065,  8.95      ],
       [ 5.70731707,  6.41463415,  7.1097561 ,  7.08860759,  6.2195122 ,
         7.93589744,  7.7037037 ,  6.18421053,  6.66197183,  6.12195122],
       [ 7.84285714,  7.86956522,  7.56716418,  7.98701299,  8.57142857,
         6.80519481,  6.89473684,  6.55405405,  6.2278481 ,  7.79545455],
       [ 5.21794872,  5.953125  ,  7.875     ,  8.08974359,  6.97777778,
         5.375     ,  7.08333333,  5.88571429

In [51]:
import warnings
warnings.filterwarnings('ignore')

FieldGoals / Games

array([[12.225     , 10.55844156,  9.45121951,  9.75609756,  9.80821918,
         9.02439024,  9.89655172,  9.46153846,  5.16666667,  7.6       ],
       [ 7.70731707,  9.40350877,  7.8902439 ,  7.84810127,  8.35526316,
         7.13888889,  7.05      ,  6.18055556,  5.84810127,  5.575     ],
       [11.07594937,  9.8974359 , 10.58666667,  9.74074074, 10.10526316,
         9.59493671, 10.01612903, 10.06578947,  9.96103896,  9.04347826],
       [ 9.45      , 10.63076923,  9.45454545,  8.10606061,  9.97101449,
         8.88311688,  8.01818182,  9.98507463,  9.64935065,  8.95      ],
       [ 5.70731707,  6.41463415,  7.1097561 ,  7.08860759,  6.2195122 ,
         7.93589744,  7.7037037 ,  6.18421053,  6.66197183,  6.12195122],
       [ 7.84285714,  7.86956522,  7.56716418,  7.98701299,  8.57142857,
         6.80519481,  6.89473684,  6.55405405,  6.2278481 ,  7.79545455],
       [ 5.21794872,  5.953125  ,  7.875     ,  8.08974359,  6.97777778,
         5.375     ,  7.08333333,  5.88571429

In [53]:
import warnings
warnings.filterwarnings('ignore')

FieldGoalsPerGame = np.matrix.round(FieldGoals / Games)

In [54]:
FieldGoalsPerGame

array([[12., 11.,  9., 10., 10.,  9., 10.,  9.,  5.,  8.],
       [ 8.,  9.,  8.,  8.,  8.,  7.,  7.,  6.,  6.,  6.],
       [11., 10., 11., 10., 10., 10., 10., 10., 10.,  9.],
       [ 9., 11.,  9.,  8., 10.,  9.,  8., 10., 10.,  9.],
       [ 6.,  6.,  7.,  7.,  6.,  8.,  8.,  6.,  7.,  6.],
       [ 8.,  8.,  8.,  8.,  9.,  7.,  7.,  7.,  6.,  8.],
       [ 5.,  6.,  8.,  8.,  7.,  5.,  7.,  6.,  7.,  7.],
       [ 9.,  9.,  7.,  9., 10.,  9., 10.,  9., 10.,  9.],
       [ 5.,  5.,  5.,  7.,  9.,  9.,  8., nan,  6.,  7.],
       [ 9.,  9.,  9., 11.,  9.,  9.,  8.,  8.,  8.,  8.]])

In [55]:
FieldGoalsPerGame[Pdict["DerrickRose"]][Sdict["2009"]]

9.0

In [56]:
FieldGoalsPerGame[Pdict["KobeBryant"]][Sdict["2009"]]

10.0

In [59]:
MinutesPlayed

array([[3277, 3140, 3192, 2960, 2835, 2779, 2232, 3013,  177, 1207],
       [3340, 2359, 3343, 3124, 2886, 2554, 2127, 2642, 2575, 2791],
       [3361, 3190, 3027, 3054, 2966, 3063, 2326, 2877, 2902, 2493],
       [2941, 2486, 2806, 2277, 2634, 2751, 1876, 2482, 2982, 1428],
       [3021, 3023, 3088, 2821, 2843, 2935, 2070, 2722, 2396, 1223],
       [2751, 2658, 2425, 2928, 2526, 2795, 2007, 2454, 2531, 1556],
       [2808, 2353, 3006, 3002, 1712, 2880, 2181, 2335, 2171, 2857],
       [1255, 1255, 2768, 2885, 3239, 3038, 2546, 3119, 3122,  913],
       [1168, 1168, 1168, 3000, 2871, 3026, 1375,    0,  311, 1530],
       [2892, 1931, 1954, 3048, 2792, 2823, 1625, 2391, 1775, 1971]])

In [60]:
np.matrix.round(MinutesPlayed / Games)

array([[41., 41., 39., 36., 39., 34., 38., 39., 30., 34.],
       [41., 41., 41., 40., 38., 35., 35., 37., 33., 35.],
       [43., 41., 40., 38., 39., 39., 38., 38., 38., 36.],
       [37., 38., 36., 34., 38., 36., 34., 37., 39., 36.],
       [37., 37., 38., 36., 35., 38., 38., 36., 34., 30.],
       [39., 39., 36., 38., 36., 36., 35., 33., 32., 35.],
       [36., 37., 38., 38., 38., 36., 36., 33., 35., 35.],
       [36., 36., 35., 39., 40., 39., 39., 39., 39., 34.],
       [29., 29., 29., 37., 37., 37., 35., nan, 31., 30.],
       [39., 38., 38., 39., 36., 37., 33., 35., 33., 32.]])

In [61]:
FieldGoals

array([[978, 813, 775, 800, 716, 740, 574, 738,  31, 266],
       [632, 536, 647, 620, 635, 514, 423, 445, 462, 446],
       [875, 772, 794, 789, 768, 758, 621, 765, 767, 624],
       [756, 691, 728, 535, 688, 684, 441, 669, 743, 358],
       [468, 526, 583, 560, 510, 619, 416, 470, 473, 251],
       [549, 543, 507, 615, 600, 524, 393, 485, 492, 343],
       [407, 381, 630, 631, 314, 430, 425, 412, 406, 568],
       [306, 306, 587, 661, 794, 711, 643, 731, 849, 238],
       [208, 208, 208, 574, 672, 711, 302,   0,  58, 338],
       [699, 472, 439, 854, 719, 692, 416, 569, 415, 509]])

In [62]:
FieldGoalAttempts

array([[2173, 1757, 1690, 1712, 1569, 1639, 1336, 1595,   73,  713],
       [1395, 1139, 1497, 1420, 1386, 1161,  931, 1052, 1018, 1025],
       [1823, 1621, 1642, 1613, 1528, 1485, 1169, 1354, 1353, 1279],
       [1572, 1453, 1481, 1207, 1502, 1503, 1025, 1489, 1643,  806],
       [ 881,  873,  974,  979,  834, 1044,  726,  813,  800,  423],
       [1087, 1094, 1027, 1263, 1158, 1056,  807,  907,  953,  745],
       [ 947,  871, 1291, 1255,  637,  928,  890,  856,  870, 1170],
       [ 647,  647, 1366, 1390, 1668, 1538, 1297, 1433, 1688,  467],
       [ 436,  436,  436, 1208, 1373, 1597,  695,    0,  164,  835],
       [1413,  962,  937, 1739, 1511, 1384,  837, 1093,  761, 1084]])

In [63]:
np.matrix.round(FieldGoals / FieldGoalAttempts)

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  1.,  1.,  1.,  1.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  0.,  0.,  0.,  1.,  0.,  0.,  1.,  1.,  0.],
       [ 0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  1.,  1.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0., nan,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  1.,  0.]])

In [64]:
np.matrix.round(FieldGoals / FieldGoalAttempts, 2)

array([[0.45, 0.46, 0.46, 0.47, 0.46, 0.45, 0.43, 0.46, 0.42, 0.37],
       [0.45, 0.47, 0.43, 0.44, 0.46, 0.44, 0.45, 0.42, 0.45, 0.44],
       [0.48, 0.48, 0.48, 0.49, 0.5 , 0.51, 0.53, 0.56, 0.57, 0.49],
       [0.48, 0.48, 0.49, 0.44, 0.46, 0.46, 0.43, 0.45, 0.45, 0.44],
       [0.53, 0.6 , 0.6 , 0.57, 0.61, 0.59, 0.57, 0.58, 0.59, 0.59],
       [0.51, 0.5 , 0.49, 0.49, 0.52, 0.5 , 0.49, 0.53, 0.52, 0.46],
       [0.43, 0.44, 0.49, 0.5 , 0.49, 0.46, 0.48, 0.48, 0.47, 0.49],
       [0.47, 0.47, 0.43, 0.48, 0.48, 0.46, 0.5 , 0.51, 0.5 , 0.51],
       [0.48, 0.48, 0.48, 0.48, 0.49, 0.45, 0.43,  nan, 0.35, 0.4 ],
       [0.49, 0.49, 0.47, 0.49, 0.48, 0.5 , 0.5 , 0.52, 0.55, 0.47]])

In [69]:
FG_Percent = np.matrix.round(FieldGoals / FieldGoalAttempts * 100, 1)

In [70]:
FG_Percent

array([[45. , 46.3, 45.9, 46.7, 45.6, 45.1, 43. , 46.3, 42.5, 37.3],
       [45.3, 47.1, 43.2, 43.7, 45.8, 44.3, 45.4, 42.3, 45.4, 43.5],
       [48. , 47.6, 48.4, 48.9, 50.3, 51. , 53.1, 56.5, 56.7, 48.8],
       [48.1, 47.6, 49.2, 44.3, 45.8, 45.5, 43. , 44.9, 45.2, 44.4],
       [53.1, 60.3, 59.9, 57.2, 61.2, 59.3, 57.3, 57.8, 59.1, 59.3],
       [50.5, 49.6, 49.4, 48.7, 51.8, 49.6, 48.7, 53.5, 51.6, 46. ],
       [43. , 43.7, 48.8, 50.3, 49.3, 46.3, 47.8, 48.1, 46.7, 48.5],
       [47.3, 47.3, 43. , 47.6, 47.6, 46.2, 49.6, 51. , 50.3, 51. ],
       [47.7, 47.7, 47.7, 47.5, 48.9, 44.5, 43.5,  nan, 35.4, 40.5],
       [49.5, 49.1, 46.9, 49.1, 47.6, 50. , 49.7, 52.1, 54.5, 47. ]])

In [71]:
FG_Percent[Pdict["LeBronJames"]][Sdict["2012"]]

56.5

In [72]:
FG_Percent[Pdict["LeBronJames"]]

array([48. , 47.6, 48.4, 48.9, 50.3, 51. , 53.1, 56.5, 56.7, 48.8])

In [74]:
Points_Per_Game = np.matrix.round(Points / Games, 1)

In [75]:
Points_Per_Game

array([[35.4, 31.6, 28.3, 26.8, 27. , 25.3, 27.9, 27.3, 13.8, 22.3],
       [20.2, 25. , 21.7, 21.4, 21.3, 18.2, 18.8, 16.2, 15.8, 14.4],
       [31.4, 27.3, 30. , 28.4, 29.7, 26.7, 27.1, 26.8, 27.1, 25.3],
       [26.5, 28.9, 25.7, 22.8, 28.2, 25.6, 22.6, 28.7, 27.4, 24.2],
       [15.8, 17.6, 20.7, 20.6, 18.3, 22.9, 20.6, 17.1, 18.3, 15.8],
       [22.5, 22.6, 22.3, 22.7, 24. , 18.7, 18. , 16.6, 16.2, 21.1],
       [16.1, 17.2, 21. , 22.8, 18.7, 15.8, 19.8, 16.9, 19.1, 19.1],
       [25.8, 25.8, 20.3, 25.3, 30.1, 27.7, 28. , 28.1, 32. , 25.4],
       [14.9, 14.9, 14.9, 16.8, 20.8, 25. , 21.8,  nan, 15.9, 17.7],
       [27.2, 27.4, 24.6, 30.2, 26.6, 25.5, 22.1, 21.2, 19. , 21.5]])

In [76]:
Points_Per_Game[Pdict["LeBronJames"]]

array([31.4, 27.3, 30. , 28.4, 29.7, 26.7, 27.1, 26.8, 27.1, 25.3])

In [77]:
from scipy.stats import pearsonr

In [81]:
corr, p = pearsonr(FG_Percent[Pdict["LeBronJames"]], Points_Per_Game[Pdict["LeBronJames"]])

In [82]:
corr

-0.3993768314113203

In [83]:
p

0.2528806821944037

In [84]:
Salary

array([[15946875, 17718750, 19490625, 21262500, 23034375, 24806250,
        25244493, 27849149, 30453805, 23500000],
       [12000000, 12744189, 13488377, 14232567, 14976754, 16324500,
        18038573, 19752645, 21466718, 23180790],
       [ 4621800,  5828090, 13041250, 14410581, 15779912, 14500000,
        16022500, 17545000, 19067500, 20644400],
       [ 3713640,  4694041, 13041250, 14410581, 15779912, 17149243,
        18518574, 19450000, 22407474, 22458000],
       [ 4493160,  4806720,  6061274, 13758000, 15202590, 16647180,
        18091770, 19536360, 20513178, 21436271],
       [ 3348000,  4235220, 12455000, 14410581, 15779912, 14500000,
        16022500, 17545000, 19067500, 20644400],
       [ 3144240,  3380160,  3615960,  4574189, 13520500, 14940153,
        16359805, 17779458, 18668431, 20068563],
       [       0,        0,  4171200,  4484040,  4796880,  6053663,
        15506632, 16669630, 17832627, 18995624],
       [       0,        0,        0,  4822800,  5184480,  55461

In [85]:
Salary[Pdict["LeBronJames"]]

array([ 4621800,  5828090, 13041250, 14410581, 15779912, 14500000,
       16022500, 17545000, 19067500, 20644400])

In [86]:
corr2, p2 = pearsonr(FG_Percent[Pdict["LeBronJames"]], Salary[Pdict["LeBronJames"]])

In [87]:
corr2

0.5904296020372817

In [88]:
p2

0.07232473788921598

In [89]:
corr3, p3 = pearsonr(Points_Per_Game[Pdict["LeBronJames"]], Salary[Pdict["LeBronJames"]])

In [90]:
corr3

-0.6186448572917211

In [91]:
p3

0.056549504612313936

In [108]:
CombinedFieldGoals = FieldGoals.flatten()

In [109]:
CombinedFieldGoals

array([978, 813, 775, 800, 716, 740, 574, 738,  31, 266, 632, 536, 647,
       620, 635, 514, 423, 445, 462, 446, 875, 772, 794, 789, 768, 758,
       621, 765, 767, 624, 756, 691, 728, 535, 688, 684, 441, 669, 743,
       358, 468, 526, 583, 560, 510, 619, 416, 470, 473, 251, 549, 543,
       507, 615, 600, 524, 393, 485, 492, 343, 407, 381, 630, 631, 314,
       430, 425, 412, 406, 568, 306, 306, 587, 661, 794, 711, 643, 731,
       849, 238, 208, 208, 208, 574, 672, 711, 302,   0,  58, 338, 699,
       472, 439, 854, 719, 692, 416, 569, 415, 509])

In [110]:
CombinedFieldGoalAttempts = FieldGoalAttempts.flatten()

In [111]:
CombinedFieldGoalAttempts

array([2173, 1757, 1690, 1712, 1569, 1639, 1336, 1595,   73,  713, 1395,
       1139, 1497, 1420, 1386, 1161,  931, 1052, 1018, 1025, 1823, 1621,
       1642, 1613, 1528, 1485, 1169, 1354, 1353, 1279, 1572, 1453, 1481,
       1207, 1502, 1503, 1025, 1489, 1643,  806,  881,  873,  974,  979,
        834, 1044,  726,  813,  800,  423, 1087, 1094, 1027, 1263, 1158,
       1056,  807,  907,  953,  745,  947,  871, 1291, 1255,  637,  928,
        890,  856,  870, 1170,  647,  647, 1366, 1390, 1668, 1538, 1297,
       1433, 1688,  467,  436,  436,  436, 1208, 1373, 1597,  695,    0,
        164,  835, 1413,  962,  937, 1739, 1511, 1384,  837, 1093,  761,
       1084])

In [113]:
CombinedFieldGoalPercent = CombinedFieldGoals / CombinedFieldGoalAttempts

In [114]:
CombinedFieldGoalPercent

array([0.45006903, 0.46272055, 0.45857988, 0.46728972, 0.45634162,
       0.45149481, 0.42964072, 0.46269592, 0.42465753, 0.37307153,
       0.45304659, 0.47058824, 0.43219773, 0.43661972, 0.45815296,
       0.44272179, 0.45435016, 0.4230038 , 0.45383104, 0.43512195,
       0.47997806, 0.47624923, 0.48355664, 0.48915065, 0.5026178 ,
       0.51043771, 0.53122327, 0.56499261, 0.5668884 , 0.48788116,
       0.48091603, 0.47556779, 0.49155976, 0.44324772, 0.45805593,
       0.45508982, 0.4302439 , 0.44929483, 0.45222155, 0.44416873,
       0.53121453, 0.60252005, 0.59856263, 0.57201226, 0.61151079,
       0.59291188, 0.57300275, 0.57810578, 0.59125   , 0.59338061,
       0.5050598 , 0.49634369, 0.49367089, 0.48693587, 0.51813472,
       0.49621212, 0.48698885, 0.53472988, 0.51626443, 0.46040268,
       0.42977825, 0.43742824, 0.4879938 , 0.50278884, 0.49293564,
       0.46336207, 0.47752809, 0.48130841, 0.46666667, 0.48547009,
       0.47295209, 0.47295209, 0.42972182, 0.47553957, 0.47601

In [115]:
CombinedSalary = Salary.flatten()

In [102]:
CombinedSalary

array([15946875, 17718750, 19490625, 21262500, 23034375, 24806250,
       25244493, 27849149, 30453805, 23500000, 12000000, 12744189,
       13488377, 14232567, 14976754, 16324500, 18038573, 19752645,
       21466718, 23180790,  4621800,  5828090, 13041250, 14410581,
       15779912, 14500000, 16022500, 17545000, 19067500, 20644400,
        3713640,  4694041, 13041250, 14410581, 15779912, 17149243,
       18518574, 19450000, 22407474, 22458000,  4493160,  4806720,
        6061274, 13758000, 15202590, 16647180, 18091770, 19536360,
       20513178, 21436271,  3348000,  4235220, 12455000, 14410581,
       15779912, 14500000, 16022500, 17545000, 19067500, 20644400,
        3144240,  3380160,  3615960,  4574189, 13520500, 14940153,
       16359805, 17779458, 18668431, 20068563,        0,        0,
        4171200,  4484040,  4796880,  6053663, 15506632, 16669630,
       17832627, 18995624,        0,        0,        0,  4822800,
        5184480,  5546160,  6993708, 16402500, 17632688, 18862

In [116]:
corr4, p4 = pearsonr(CombinedFieldGoalPercent, CombinedSalary)

ValueError: array must not contain infs or NaNs

In [117]:
CombinedFieldGoalPercent2 = CombinedFieldGoalPercent[np.logical_not(np.isnan(CombinedFieldGoalPercent))]

In [118]:
CombinedFieldGoalPercent2

array([0.45006903, 0.46272055, 0.45857988, 0.46728972, 0.45634162,
       0.45149481, 0.42964072, 0.46269592, 0.42465753, 0.37307153,
       0.45304659, 0.47058824, 0.43219773, 0.43661972, 0.45815296,
       0.44272179, 0.45435016, 0.4230038 , 0.45383104, 0.43512195,
       0.47997806, 0.47624923, 0.48355664, 0.48915065, 0.5026178 ,
       0.51043771, 0.53122327, 0.56499261, 0.5668884 , 0.48788116,
       0.48091603, 0.47556779, 0.49155976, 0.44324772, 0.45805593,
       0.45508982, 0.4302439 , 0.44929483, 0.45222155, 0.44416873,
       0.53121453, 0.60252005, 0.59856263, 0.57201226, 0.61151079,
       0.59291188, 0.57300275, 0.57810578, 0.59125   , 0.59338061,
       0.5050598 , 0.49634369, 0.49367089, 0.48693587, 0.51813472,
       0.49621212, 0.48698885, 0.53472988, 0.51626443, 0.46040268,
       0.42977825, 0.43742824, 0.4879938 , 0.50278884, 0.49293564,
       0.46336207, 0.47752809, 0.48130841, 0.46666667, 0.48547009,
       0.47295209, 0.47295209, 0.42972182, 0.47553957, 0.47601

In [119]:
CombinedFieldGoalPercent

array([0.45006903, 0.46272055, 0.45857988, 0.46728972, 0.45634162,
       0.45149481, 0.42964072, 0.46269592, 0.42465753, 0.37307153,
       0.45304659, 0.47058824, 0.43219773, 0.43661972, 0.45815296,
       0.44272179, 0.45435016, 0.4230038 , 0.45383104, 0.43512195,
       0.47997806, 0.47624923, 0.48355664, 0.48915065, 0.5026178 ,
       0.51043771, 0.53122327, 0.56499261, 0.5668884 , 0.48788116,
       0.48091603, 0.47556779, 0.49155976, 0.44324772, 0.45805593,
       0.45508982, 0.4302439 , 0.44929483, 0.45222155, 0.44416873,
       0.53121453, 0.60252005, 0.59856263, 0.57201226, 0.61151079,
       0.59291188, 0.57300275, 0.57810578, 0.59125   , 0.59338061,
       0.5050598 , 0.49634369, 0.49367089, 0.48693587, 0.51813472,
       0.49621212, 0.48698885, 0.53472988, 0.51626443, 0.46040268,
       0.42977825, 0.43742824, 0.4879938 , 0.50278884, 0.49293564,
       0.46336207, 0.47752809, 0.48130841, 0.46666667, 0.48547009,
       0.47295209, 0.47295209, 0.42972182, 0.47553957, 0.47601

In [120]:
CombinedSalary2 = CombinedSalary[np.logical_not(np.isnan(CombinedFieldGoalPercent))]

In [121]:
CombinedSalary2

array([15946875, 17718750, 19490625, 21262500, 23034375, 24806250,
       25244493, 27849149, 30453805, 23500000, 12000000, 12744189,
       13488377, 14232567, 14976754, 16324500, 18038573, 19752645,
       21466718, 23180790,  4621800,  5828090, 13041250, 14410581,
       15779912, 14500000, 16022500, 17545000, 19067500, 20644400,
        3713640,  4694041, 13041250, 14410581, 15779912, 17149243,
       18518574, 19450000, 22407474, 22458000,  4493160,  4806720,
        6061274, 13758000, 15202590, 16647180, 18091770, 19536360,
       20513178, 21436271,  3348000,  4235220, 12455000, 14410581,
       15779912, 14500000, 16022500, 17545000, 19067500, 20644400,
        3144240,  3380160,  3615960,  4574189, 13520500, 14940153,
       16359805, 17779458, 18668431, 20068563,        0,        0,
        4171200,  4484040,  4796880,  6053663, 15506632, 16669630,
       17832627, 18995624,        0,        0,        0,  4822800,
        5184480,  5546160,  6993708, 17632688, 18862875,  3031

In [122]:
CombinedSalary

array([15946875, 17718750, 19490625, 21262500, 23034375, 24806250,
       25244493, 27849149, 30453805, 23500000, 12000000, 12744189,
       13488377, 14232567, 14976754, 16324500, 18038573, 19752645,
       21466718, 23180790,  4621800,  5828090, 13041250, 14410581,
       15779912, 14500000, 16022500, 17545000, 19067500, 20644400,
        3713640,  4694041, 13041250, 14410581, 15779912, 17149243,
       18518574, 19450000, 22407474, 22458000,  4493160,  4806720,
        6061274, 13758000, 15202590, 16647180, 18091770, 19536360,
       20513178, 21436271,  3348000,  4235220, 12455000, 14410581,
       15779912, 14500000, 16022500, 17545000, 19067500, 20644400,
        3144240,  3380160,  3615960,  4574189, 13520500, 14940153,
       16359805, 17779458, 18668431, 20068563,        0,        0,
        4171200,  4484040,  4796880,  6053663, 15506632, 16669630,
       17832627, 18995624,        0,        0,        0,  4822800,
        5184480,  5546160,  6993708, 16402500, 17632688, 18862

In [123]:
corr5, p5 = pearsonr(CombinedFieldGoalPercent2, CombinedSalary2)

In [124]:
corr5

-0.07125156557930769

In [125]:
p5

0.48340795503912437

In [134]:
CombinedPoints = Points.flatten()

In [135]:
CombinedPoints

array([2832, 2430, 2323, 2201, 1970, 2078, 1616, 2133,   83,  782, 1653,
       1426, 1779, 1688, 1619, 1312, 1129, 1170, 1245, 1154, 2478, 2132,
       2250, 2304, 2258, 2111, 1683, 2036, 2089, 1743, 2122, 1881, 1978,
       1504, 1943, 1970, 1245, 1920, 2112,  966, 1292, 1443, 1695, 1624,
       1503, 1784, 1113, 1296, 1297,  646, 1572, 1561, 1496, 1746, 1678,
       1438, 1025, 1232, 1281,  928, 1258, 1104, 1684, 1781,  841, 1268,
       1189, 1186, 1185, 1564,  903,  903, 1624, 1871, 2472, 2161, 1850,
       2280, 2593,  686,  597,  597,  597, 1361, 1619, 2026,  852,    0,
        159,  904, 2040, 1397, 1254, 2386, 2045, 1941, 1082, 1463, 1028,
       1331])

In [136]:
CombinedGames = Games.flatten()

In [137]:
CombinedGames

array([80, 77, 82, 82, 73, 82, 58, 78,  6, 35, 82, 57, 82, 79, 76, 72, 60,
       72, 79, 80, 79, 78, 75, 81, 76, 79, 62, 76, 77, 69, 80, 65, 77, 66,
       69, 77, 55, 67, 77, 40, 82, 82, 82, 79, 82, 78, 54, 76, 71, 41, 70,
       69, 67, 77, 70, 77, 57, 74, 79, 44, 78, 64, 80, 78, 45, 80, 60, 70,
       62, 82, 35, 35, 80, 74, 82, 78, 66, 81, 81, 27, 40, 40, 40, 81, 78,
       81, 39,  0, 10, 51, 75, 51, 51, 79, 77, 76, 49, 69, 54, 62])

In [138]:
CombinedPointsPerGame = Points / Games

In [139]:
CombinedPointsPerGame

array([[35.4       , 31.55844156, 28.32926829, 26.84146341, 26.98630137,
        25.34146341, 27.86206897, 27.34615385, 13.83333333, 22.34285714],
       [20.15853659, 25.01754386, 21.69512195, 21.36708861, 21.30263158,
        18.22222222, 18.81666667, 16.25      , 15.75949367, 14.425     ],
       [31.36708861, 27.33333333, 30.        , 28.44444444, 29.71052632,
        26.72151899, 27.14516129, 26.78947368, 27.12987013, 25.26086957],
       [26.525     , 28.93846154, 25.68831169, 22.78787879, 28.15942029,
        25.58441558, 22.63636364, 28.65671642, 27.42857143, 24.15      ],
       [15.75609756, 17.59756098, 20.67073171, 20.55696203, 18.32926829,
        22.87179487, 20.61111111, 17.05263158, 18.26760563, 15.75609756],
       [22.45714286, 22.62318841, 22.32835821, 22.67532468, 23.97142857,
        18.67532468, 17.98245614, 16.64864865, 16.21518987, 21.09090909],
       [16.12820513, 17.25      , 21.05      , 22.83333333, 18.68888889,
        15.85      , 19.81666667, 16.94285714

In [140]:
CombinedPointsPerGame2 = CombinedPointsPerGame[np.logical_not(np.isnan(CombinedPointsPerGame))]

In [141]:
CombinedPointsPerGame2

array([35.4       , 31.55844156, 28.32926829, 26.84146341, 26.98630137,
       25.34146341, 27.86206897, 27.34615385, 13.83333333, 22.34285714,
       20.15853659, 25.01754386, 21.69512195, 21.36708861, 21.30263158,
       18.22222222, 18.81666667, 16.25      , 15.75949367, 14.425     ,
       31.36708861, 27.33333333, 30.        , 28.44444444, 29.71052632,
       26.72151899, 27.14516129, 26.78947368, 27.12987013, 25.26086957,
       26.525     , 28.93846154, 25.68831169, 22.78787879, 28.15942029,
       25.58441558, 22.63636364, 28.65671642, 27.42857143, 24.15      ,
       15.75609756, 17.59756098, 20.67073171, 20.55696203, 18.32926829,
       22.87179487, 20.61111111, 17.05263158, 18.26760563, 15.75609756,
       22.45714286, 22.62318841, 22.32835821, 22.67532468, 23.97142857,
       18.67532468, 17.98245614, 16.64864865, 16.21518987, 21.09090909,
       16.12820513, 17.25      , 21.05      , 22.83333333, 18.68888889,
       15.85      , 19.81666667, 16.94285714, 19.11290323, 19.07

In [142]:
corr6, p6 = pearsonr(CombinedFieldGoalPercent2, CombinedPointsPerGame2)

In [143]:
corr6

-0.037361130049047224

In [144]:
p6

0.713510402696166

In [145]:
corr7, p7 = pearsonr(CombinedPointsPerGame2, CombinedSalary2)

In [146]:
corr7

0.009703276839176943

In [147]:
p7

0.9240587062433419